# Moview Recommendation System

## Data Loading & Feature Selection

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies = pd.read_csv("./movies.csv")

In [3]:
movies.head(10)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
5,5,258000000,Fantasy Action Adventure,http://www.sonypictures.com/movies/spider-man3/,559,dual identity amnesia sandstorm love of one's ...,en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,...,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576,Tobey Maguire Kirsten Dunst James Franco Thoma...,"[{'name': 'Francine Maisler', 'gender': 1, 'de...",Sam Raimi
6,6,260000000,Animation Family,http://disney.go.com/disneypictures/tangled/,38757,hostage magic horse fairy tale musical,en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,...,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330,Zachary Levi Mandy Moore Donna Murphy Ron Perl...,"[{'name': 'John Lasseter', 'gender': 2, 'depar...",Byron Howard
7,7,280000000,Action Adventure Science Fiction,http://marvel.com/movies/movie/193/avengers_ag...,99861,marvel comic sequel superhero based on comic b...,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,...,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767,Robert Downey Jr. Chris Hemsworth Mark Ruffalo...,"[{'name': 'Danny Elfman', 'gender': 2, 'depart...",Joss Whedon
8,8,250000000,Adventure Fantasy Family,http://harrypotter.warnerbros.com/harrypottera...,767,witch magic broom school of witchcraft wizardry,en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,...,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293,Daniel Radcliffe Rupert Grint Emma Watson Tom ...,"[{'name': 'Bruno Delbonnel', 'gender': 0, 'dep...",David Yates
9,9,250000000,Action Adventure Fantasy,http://www.batmanvsupermandawnofjustice.com/,209112,dc comics vigilante superhero based on comic b...,en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,...,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004,Ben Affleck Henry Cavill Gal Gadot Amy Adams J...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Zack Snyder

In [4]:
movies.shape

(4803, 24)

In [5]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   str
 3   homepage              1712 non-null   str
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   str
 6   original_language     4803 non-null   str
 7   original_title        4803 non-null   str
 8   overview              4800 non-null   str
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   str
 11  production_countries  4803 non-null   str
 12  release_date          4802 non-null   str
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   str
 16  status                4803 non-null   str
 17  tagline               3959 non-null   str
 18  title                 4803 non-null   str
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   str
 22  crew                  4803 non-null   str
 23  director              4773 non-null   str
dtypes: float64(3), int64(5), str(16)
memory usage: 900.7 KB

In [6]:
movies.describe()

,index,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4803.000000,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2401.000000,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,1386.651002,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,1200.500000,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,2401.000000,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,3601.500000,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,4802.000000,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [7]:
selected_features = ['index','title','genres','keywords','overview','cast','director']
print(selected_features)

['index', 'title', 'genres', 'keywords', 'overview', 'cast', 'director']

In [8]:
movies_filtered = movies[selected_features]

In [9]:
movies_filtered

,index,title,genres,keywords,overview,cast,director
0,0,Avatar,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,"In the 22nd century, a paraplegic Marine is di...",Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron
1,1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,"Captain Barbossa, long believed to be dead, ha...",Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski
2,2,Spectre,Action Adventure Crime,spy based on novel secret agent sequel mi6,A cryptic message from Bond’s past sends him o...,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,Sam Mendes
3,3,The Dark Knight Rises,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,Following the death of District Attorney Harve...,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan
4,4,John Carter,Action Adventure Science Fiction,based on novel mars medallion space travel pri...,"John Carter is a war-weary, former military ca...",Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton
...,...,...,...,...,...,...,...
4798,4798,El Mariachi,Action Crime Thriller,united states\u2013mexico barrier legs arms pa...,El Mariachi just wants to play his guitar and ...,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,Robert Rodriguez
4799,4799,Newlyweds,Comedy Romance,NaN,A newlywed couple's honeymoon is upended by th...,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,Edward Burns
4800,4800,"Signed, Sealed, Delivered",Comedy Drama Romance TV Movie,date love at first sight narration investigati...,"""Signed, Sealed, Delivered"" introduces a dedic...",Eric Mabius Kristin Booth Crystal Lowe Geoff G...,Scott Smith
4801,4801,Shanghai Calling,NaN,NaN,When ambitious New York attorney Sam is sent t...,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,Daniel Hsia
4802,4802,My Date with Drew,Documentary,obsession camcorder crush dream girl,Ever since the second grade when he first saw ...,Drew Barrymore Brian Herzlinger Corey Feldman ...,Brian Herzlinger

## Text Preprocessing

In [10]:
for feature in selected_features:
  movies_filtered[feature] = movies_filtered[feature].fillna('')

In [11]:
combined_features = movies_filtered['genres']+' '+movies_filtered['keywords']+' '+movies_filtered['overview']+' '+movies_filtered['cast']+' '+movies_filtered['director']

In [12]:
combined_features.head(3)

0    Action Adventure Fantasy Science Fiction cultu...
1    Adventure Fantasy Action ocean drug abuse exot...
2    Action Adventure Crime spy based on novel secr...
dtype: str

## Build TF-IDF Matrix

In [13]:
vectorizer = TfidfVectorizer(stop_words='english')

In [14]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [15]:
feature_vectors.shape

(4803, 29804)

## Compute Cosine Similarity

In [16]:
similarity = cosine_similarity(feature_vectors)

In [17]:
similarity.shape

(4803, 4803)

## Recommendation Function

In [21]:
movie_name = input('Enter your favourite movie name : ')

In [22]:
list_of_all_titles = movies_filtered['title'].tolist()
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
close_match = find_close_match[0]

In [23]:
index_of_the_movie = movies_filtered[movies_filtered.title == close_match]['index'].values[0]

In [24]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))

In [25]:
sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)

In [27]:
print('Movies suggested for you :\n')
i = 1
for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_filtered[movies_filtered.index == index]['title'].values
    if i < 30:
        print(i, '.', title_from_index[0])
        i += 1

Movies suggested for you :

1 . Avatar
2 . Lifeforce
3 . Star Trek Beyond
4 . Guardians of the Galaxy
5 . Gattaca
6 . Moonraker
7 . Aliens
8 . Lockout
9 . Alien
10 . Gravity
11 . The Helix... Loaded
12 . Lost in Space
13 . Apollo 18
14 . Zathura: A Space Adventure
15 . Treasure Planet
16 . Space Chimps
17 . Cargo
18 . Trekkies
19 . Sunshine
20 . Star Trek Into Darkness
21 . Machete Kills
22 . Silent Running
23 . Men in Black II
24 . The Book of Life
25 . Alien³
26 . Imaginary Heroes
27 . Sphere
28 . Deep Impact
29 . Terminator Salvation